### ISSUE TITLE
Updated Featured Posts Block to use RUM data for "most popular"

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/blogs-keysight#19]

**Comment by rrusher** [comment]
RUM data, if time boxed (i.e. created in the last 6 months), could be useful. Without the time box, I wouldn't recommend it because the "most popular" has to take time into account. The most popular (song, movie, phrase, etc.) changes over time.

**Comment by rrusher** [comment]
Looks like you can set the granularity: https://www.hlx.live/developer/rum#rum-pageviews
