### ISSUE TITLE
integrate tags from AEM

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/blogs-keysight#43]
We will create 2 tag fields:

* Tags 
  * only used for blog posts
  * end user facing
  * sourced from aem tag namespace ` /content/cq:tags/keysight-blogs`
  * in word doc we will store the tag name, tag title will be displayed to end user
* Back-Office Tags
  * can be added to any page, not just blog posts
  * used for meta tags
  * sourced from aem tag namespace `/content/cq:tags/segmentation`
  * in word doc we will store the tag name
  * meta tags are added to the head such as `<meta name="<parent tag name>" content="<tag name>"/> `
    * for each segmentation tag added, add a meta element to the document
    * the content property is simply the tag name from the json feed
    * the name property is the tag name of the parent tag (that is, take the tag path, find the parent tag, and get it's name. if the parent is missing for some reason the just use the path slug).

Both tags and back office tags are subject to validation, and should be checked by preflight.

We also need to update the tagger to support selecting these 2 types of tags (and not showing back office tags when user is selecting tags, or vice versa)

**Comment by rrusher** [comment]
English Tags: https://www.keysight.com/clientapi/search/aemtags/en
Since this is via Akamai you don’t need API Key. The above will fetch for English, for other languages we will have to replace the language code at the end:
Japan : https://www.keysight.com/clientapi/search/aemtags/ja
