### ISSUE TITLE
Preflight check

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/blogs-keysight#72]
a sidekick plugin which will run in preview mode to provide authors feedback on best practices for their page.

Thinking for now is to start with what the adobe one does and add to it/change as needed based on feedback. See https://github.com/adobecom/milo/tree/main/libs/blocks/preflight

**Comment by shsteimer** [comment]
@gandal-adobe 

Checks we can look at adding, in addition to milo checks:

* all images have alt text (may need to be sure we are only checking images that are part of the page, e.g by ignoring images in certain blocks like post cards)
* blog post has a hero image
* headings are ordered correctly
* all tags are valid, see #77 
* blog post author name is valid and has an author page
* blog post has a read time and published date set and they are formatted properly
*

**Comment by gandal-adobe** [comment]
Hi @shsteimer - the preflight guide doc is:
https://main--blogs-keysight--hlxsites.hlx.page/blogs/drafts/documentation/preflight-guide

All of my changes are in the preflight branch. This covers both milo checks and the checks you listed above.
